# Generated by Django 3.2.12 on 2022-02-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
