# Generated by Django 3.2.6 on 2022-02-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_about_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Educations',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='lives_in',
            new_name='degree',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='codingskills',
            name='explanations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='gender',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
