# Generated by Django 3.2.6 on 2022-02-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20220209_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='explanation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='details',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/%Y%M%d/'),
        ),
    ]
