# Generated by Django 3.2.6 on 2022-02-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20220210_1855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesignSkills',
        ),
    ]
