# Generated by Django 3.2.6 on 2022-02-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_codingskills2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingskills',
            name='explanations',
        ),
    ]
