# Generated by Django 3.2.6 on 2022-02-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_remove_codingskills_explanations'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanations', models.TextField(null=True)),
                ('person_name', models.CharField(max_length=120)),
                ('person_job', models.CharField(max_length=120)),
                ('comments', models.TextField()),
                ('image', models.ImageField(upload_to='testimonials/photo%Y%M%d/')),
            ],
        ),
    ]
