# Generated by Django 3.2.12 on 2022-02-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_testimonials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='explanations',
        ),
    ]
