# Generated by Django 3.2.12 on 2022-03-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_contactme_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMe',
        ),
        migrations.DeleteModel(
            name='info',
        ),
    ]
