# Generated by Django 3.2.12 on 2022-03-07 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_auto_20220302_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'Abouts'},
        ),
        migrations.AlterField(
            model_name='about',
            name='age',
            field=models.IntegerField(default=15, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='about',
            name='city',
            field=models.CharField(max_length=120, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='about',
            name='degree',
            field=models.CharField(max_length=120, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='about',
            name='details',
            field=models.CharField(max_length=120, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.CharField(blank=True, max_length=120, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='about',
            name='expertise',
            field=models.CharField(max_length=120, verbose_name='Expertise'),
        ),
        migrations.AlterField(
            model_name='about',
            name='explanation',
            field=models.TextField(null=True, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='about',
            name='gender',
            field=models.CharField(blank=True, max_length=15, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/%Y%M%d/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='codingskills',
            name='skill_name',
            field=models.CharField(max_length=40, verbose_name='skill'),
        ),
        migrations.AlterField(
            model_name='codingskills',
            name='skill_rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='codingskills2',
            name='skill_name',
            field=models.CharField(max_length=40, verbose_name='skill'),
        ),
        migrations.AlterField(
            model_name='codingskills2',
            name='skill_rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='comments',
            field=models.TextField(verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(upload_to='testimonials/photo%Y%M%d/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='person_job',
            field=models.CharField(max_length=120, verbose_name='Person job'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='person_name',
            field=models.CharField(max_length=120, verbose_name='Person Name'),
        ),
    ]
