# Generated by Django 3.2.12 on 2022-03-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_auto_20220307_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='age_de',
            field=models.IntegerField(default=15, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='about',
            name='age_en',
            field=models.IntegerField(default=15, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='about',
            name='age_fa',
            field=models.IntegerField(default=15, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='about',
            name='city_de',
            field=models.CharField(max_length=120, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='about',
            name='city_en',
            field=models.CharField(max_length=120, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='about',
            name='city_fa',
            field=models.CharField(max_length=120, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='about',
            name='degree_de',
            field=models.CharField(max_length=120, null=True, verbose_name='Degree'),
        ),
        migrations.AddField(
            model_name='about',
            name='degree_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Degree'),
        ),
        migrations.AddField(
            model_name='about',
            name='degree_fa',
            field=models.CharField(max_length=120, null=True, verbose_name='Degree'),
        ),
        migrations.AddField(
            model_name='about',
            name='details_de',
            field=models.CharField(max_length=120, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='about',
            name='details_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='about',
            name='details_fa',
            field=models.CharField(max_length=120, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='about',
            name='expertise_de',
            field=models.CharField(max_length=120, null=True, verbose_name='Expertise'),
        ),
        migrations.AddField(
            model_name='about',
            name='expertise_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Expertise'),
        ),
        migrations.AddField(
            model_name='about',
            name='expertise_fa',
            field=models.CharField(max_length=120, null=True, verbose_name='Expertise'),
        ),
        migrations.AddField(
            model_name='about',
            name='explanation_de',
            field=models.TextField(null=True, verbose_name='Explanation'),
        ),
        migrations.AddField(
            model_name='about',
            name='explanation_en',
            field=models.TextField(null=True, verbose_name='Explanation'),
        ),
        migrations.AddField(
            model_name='about',
            name='explanation_fa',
            field=models.TextField(null=True, verbose_name='Explanation'),
        ),
        migrations.AddField(
            model_name='about',
            name='gender_de',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='about',
            name='gender_en',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='about',
            name='gender_fa',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Gender'),
        ),
    ]
