# Generated by Django 3.2.12 on 2022-03-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_auto_20220307_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True)),
                ('intro_en', models.TextField(blank=True, null=True)),
                ('intro_fa', models.TextField(blank=True, null=True)),
                ('intro_de', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'T_Intro',
                'verbose_name_plural': 'T_Intros',
            },
        ),
    ]
