# Generated by Django 3.2.12 on 2022-03-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_t_intro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'testimonial', 'verbose_name_plural': 'testimonials'},
        ),
        migrations.AddField(
            model_name='testimonials',
            name='comments_de',
            field=models.TextField(null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='comments_en',
            field=models.TextField(null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='comments_fa',
            field=models.TextField(null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='person_job_de',
            field=models.CharField(max_length=120, null=True, verbose_name='Person job'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='person_job_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Person job'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='person_job_fa',
            field=models.CharField(max_length=120, null=True, verbose_name='Person job'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='person_name_de',
            field=models.CharField(max_length=120, null=True, verbose_name='Person Name'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='person_name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Person Name'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='person_name_fa',
            field=models.CharField(max_length=120, null=True, verbose_name='Person Name'),
        ),
        migrations.AlterField(
            model_name='t_intro',
            name='intro',
            field=models.TextField(blank=True, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='t_intro',
            name='intro_de',
            field=models.TextField(blank=True, null=True, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='t_intro',
            name='intro_en',
            field=models.TextField(blank=True, null=True, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='t_intro',
            name='intro_fa',
            field=models.TextField(blank=True, null=True, verbose_name='introduction'),
        ),
    ]
