# Generated by Django 3.2.12 on 2022-03-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_auto_20220310_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='FACTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True)),
                ('client', models.IntegerField(default=1, verbose_name='clients')),
                ('projects', models.IntegerField(default=1, verbose_name='projects')),
                ('hour_of_support', models.IntegerField(default=1, verbose_name='hour of support')),
                ('experience', models.IntegerField(default=1, verbose_name='experience')),
            ],
            options={
                'verbose_name': 'Fact',
                'verbose_name_plural': 'Facts',
            },
        ),
        migrations.CreateModel(
            name='Skill_Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True, verbose_name='skill introduction')),
            ],
            options={
                'verbose_name': 'skill_Intro',
                'verbose_name_plural': 'skill_Intros',
            },
        ),
    ]
