# Generated by Django 3.2.12 on 2022-03-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_facts_skill_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='facts',
            name='client_de',
            field=models.IntegerField(default=1, null=True, verbose_name='clients'),
        ),
        migrations.AddField(
            model_name='facts',
            name='client_en',
            field=models.IntegerField(default=1, null=True, verbose_name='clients'),
        ),
        migrations.AddField(
            model_name='facts',
            name='client_fa',
            field=models.IntegerField(default=1, null=True, verbose_name='clients'),
        ),
        migrations.AddField(
            model_name='facts',
            name='experience_de',
            field=models.IntegerField(default=1, null=True, verbose_name='experience'),
        ),
        migrations.AddField(
            model_name='facts',
            name='experience_en',
            field=models.IntegerField(default=1, null=True, verbose_name='experience'),
        ),
        migrations.AddField(
            model_name='facts',
            name='experience_fa',
            field=models.IntegerField(default=1, null=True, verbose_name='experience'),
        ),
        migrations.AddField(
            model_name='facts',
            name='hour_of_support_de',
            field=models.IntegerField(default=1, null=True, verbose_name='hour of support'),
        ),
        migrations.AddField(
            model_name='facts',
            name='hour_of_support_en',
            field=models.IntegerField(default=1, null=True, verbose_name='hour of support'),
        ),
        migrations.AddField(
            model_name='facts',
            name='hour_of_support_fa',
            field=models.IntegerField(default=1, null=True, verbose_name='hour of support'),
        ),
        migrations.AddField(
            model_name='facts',
            name='intro_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facts',
            name='intro_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facts',
            name='intro_fa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facts',
            name='projects_de',
            field=models.IntegerField(default=1, null=True, verbose_name='projects'),
        ),
        migrations.AddField(
            model_name='facts',
            name='projects_en',
            field=models.IntegerField(default=1, null=True, verbose_name='projects'),
        ),
        migrations.AddField(
            model_name='facts',
            name='projects_fa',
            field=models.IntegerField(default=1, null=True, verbose_name='projects'),
        ),
        migrations.AddField(
            model_name='skill_intro',
            name='intro_de',
            field=models.TextField(blank=True, null=True, verbose_name='skill introduction'),
        ),
        migrations.AddField(
            model_name='skill_intro',
            name='intro_en',
            field=models.TextField(blank=True, null=True, verbose_name='skill introduction'),
        ),
        migrations.AddField(
            model_name='skill_intro',
            name='intro_fa',
            field=models.TextField(blank=True, null=True, verbose_name='skill introduction'),
        ),
    ]
