# Generated by Django 3.2.12 on 2022-03-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_auto_20220310_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='client',
            field=models.IntegerField(default=1, verbose_name='Clients'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='client_de',
            field=models.IntegerField(default=1, null=True, verbose_name='Clients'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='client_en',
            field=models.IntegerField(default=1, null=True, verbose_name='Clients'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='client_fa',
            field=models.IntegerField(default=1, null=True, verbose_name='Clients'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='experience',
            field=models.IntegerField(default=1, verbose_name='Year Of Experience'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='experience_de',
            field=models.IntegerField(default=1, null=True, verbose_name='Year Of Experience'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='experience_en',
            field=models.IntegerField(default=1, null=True, verbose_name='Year Of Experience'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='experience_fa',
            field=models.IntegerField(default=1, null=True, verbose_name='Year Of Experience'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='hour_of_support',
            field=models.IntegerField(default=1, verbose_name='Hours Of Support'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='hour_of_support_de',
            field=models.IntegerField(default=1, null=True, verbose_name='Hours Of Support'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='hour_of_support_en',
            field=models.IntegerField(default=1, null=True, verbose_name='Hours Of Support'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='hour_of_support_fa',
            field=models.IntegerField(default=1, null=True, verbose_name='Hours Of Support'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='projects',
            field=models.IntegerField(default=1, verbose_name='Projects'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='projects_de',
            field=models.IntegerField(default=1, null=True, verbose_name='Projects'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='projects_en',
            field=models.IntegerField(default=1, null=True, verbose_name='Projects'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='projects_fa',
            field=models.IntegerField(default=1, null=True, verbose_name='Projects'),
        ),
    ]
