# Generated by Django 3.2.12 on 2022-03-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_auto_20220311_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facts',
            name='client_de',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='client_en',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='client_fa',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='experience_de',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='experience_en',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='experience_fa',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='hour_of_support_de',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='hour_of_support_en',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='hour_of_support_fa',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='projects_de',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='projects_en',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='projects_fa',
        ),
    ]
