# Generated by Django 3.2.6 on 2022-02-17 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('client', models.CharField(blank=True, max_length=120)),
                ('project_date', models.DateTimeField(blank=True)),
                ('project_url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('photo_main', models.ImageField(upload_to='project/photo/%Y%M%d/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.category')),
            ],
        ),
    ]
