# Generated by Django 3.2.6 on 2022-02-12 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=150)),
                ('start', models.DateTimeField(blank=True)),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 12, 22, 43, 1, 279748))),
                ('custom_duration', models.CharField(blank=True, max_length=120)),
                ('details', models.TextField()),
            ],
        ),
    ]
