# Generated by Django 3.2.6 on 2022-02-12 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 12, 23, 6, 53, 389191), null=True),
        ),
    ]
