# Generated by Django 3.2.6 on 2022-02-13 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_alter_resume_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 13, 21, 35, 35, 878789), null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
