# Generated by Django 3.2.6 on 2022-02-13 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_auto_20220213_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 13, 21, 44, 32, 496963), null=True),
        ),
    ]
