# Generated by Django 3.2.6 on 2022-02-13 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0006_alter_resume_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('descriptins', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 13, 21, 54, 13, 992533), null=True),
        ),
    ]
