# Generated by Django 3.2.6 on 2022-02-16 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0007_auto_20220213_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=150)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 16, 13, 21, 4, 840720), null=True)),
                ('custom_duration', models.CharField(blank=True, max_length=120)),
                ('details', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='resume',
        ),
    ]
