# Generated by Django 3.2.6 on 2022-02-16 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0010_auto_20220216_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 16, 13, 43, 24, 24722), null=True),
        ),
    ]
