# Generated by Django 3.2.6 on 2022-02-16 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0012_alter_work_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educations',
            name='custom_duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='work',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 16, 13, 50, 36, 139403), null=True),
        ),
    ]
