# Generated by Django 3.2.6 on 2022-02-17 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0013_auto_20220216_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 17, 13, 0, 51, 276430), null=True),
        ),
    ]
