# Generated by Django 3.2.12 on 2022-03-21 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0025_alter_work_end'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educations',
            options={'verbose_name': 'education', 'verbose_name_plural': 'educations'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Work', 'verbose_name_plural': 'Works'},
        ),
        migrations.AddField(
            model_name='educations',
            name='custom_duration_de',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='custom duration '),
        ),
        migrations.AddField(
            model_name='educations',
            name='custom_duration_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='custom duration '),
        ),
        migrations.AddField(
            model_name='educations',
            name='custom_duration_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='custom duration '),
        ),
        migrations.AddField(
            model_name='educations',
            name='details_de',
            field=models.TextField(null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='educations',
            name='details_en',
            field=models.TextField(null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='educations',
            name='details_fa',
            field=models.TextField(null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='educations',
            name='end_de',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 10, 15, 35, 914351), null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='educations',
            name='end_en',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 10, 15, 35, 914351), null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='educations',
            name='end_fa',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 10, 15, 35, 914351), null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='educations',
            name='start_de',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AddField(
            model_name='educations',
            name='start_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AddField(
            model_name='educations',
            name='start_fa',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AddField(
            model_name='educations',
            name='sub_title_de',
            field=models.CharField(max_length=150, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='educations',
            name='sub_title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='educations',
            name='sub_title_fa',
            field=models.CharField(max_length=150, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='educations',
            name='title_de',
            field=models.CharField(max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='educations',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='educations',
            name='title_fa',
            field=models.CharField(max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='work',
            name='custom_duration_de',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='custom duration '),
        ),
        migrations.AddField(
            model_name='work',
            name='custom_duration_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='custom duration '),
        ),
        migrations.AddField(
            model_name='work',
            name='custom_duration_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='custom duration '),
        ),
        migrations.AddField(
            model_name='work',
            name='details_de',
            field=models.TextField(null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='work',
            name='details_en',
            field=models.TextField(null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='work',
            name='details_fa',
            field=models.TextField(null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='work',
            name='end_de',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 10, 15, 35, 912345), null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='work',
            name='end_en',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 10, 15, 35, 912345), null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='work',
            name='end_fa',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 10, 15, 35, 912345), null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='work',
            name='start_de',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AddField(
            model_name='work',
            name='start_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AddField(
            model_name='work',
            name='start_fa',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AddField(
            model_name='work',
            name='sub_title_de',
            field=models.CharField(max_length=150, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='work',
            name='sub_title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='work',
            name='sub_title_fa',
            field=models.CharField(max_length=150, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='work',
            name='title_de',
            field=models.CharField(max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='work',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='work',
            name='title_fa',
            field=models.CharField(max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='custom_duration',
            field=models.CharField(blank=True, max_length=120, verbose_name='custom duration '),
        ),
        migrations.AlterField(
            model_name='educations',
            name='details',
            field=models.TextField(verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 10, 15, 35, 914351), null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='sub_title',
            field=models.CharField(max_length=150, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='title',
            field=models.CharField(max_length=150, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='work',
            name='custom_duration',
            field=models.CharField(blank=True, max_length=120, verbose_name='custom duration '),
        ),
        migrations.AlterField(
            model_name='work',
            name='details',
            field=models.TextField(verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='work',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 10, 15, 35, 912345), null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='work',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='work',
            name='sub_title',
            field=models.CharField(max_length=150, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=150, verbose_name='title'),
        ),
    ]
