# Generated by Django 3.2.12 on 2022-03-21 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0026_auto_20220321_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educations',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 10, 24, 22, 100322), null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='end_de',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 10, 24, 22, 100322), null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='end_en',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 10, 24, 22, 100322), null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='end_fa',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 10, 24, 22, 100322), null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='work',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 10, 24, 22, 98323), null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_de',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 10, 24, 22, 98323), null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_en',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 10, 24, 22, 98323), null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_fa',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 21, 10, 24, 22, 98323), null=True, verbose_name='end date'),
        ),
    ]
